### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Project-Exhale** [QuickBirdEng/survey_kit#116]
I get the following error when trying to run the Example:

AppData/Local/Pub/Cache/hosted/pub.dev/flutter_platform_widgets-3.0.0/lib/src/platform.dart:297:29: Error: The argument type 'bool?' can't be assigned to the parameter type 'bool' because 'bool?' is nullable and 'bool' isn't.
      semanticsDismissible: cupertino?.semanticsDismissible,
                            ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\Flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1214

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Numoy** [comment]
If you try the latest version from main this should work again. Can you please check again?
