### ISSUE TITLE
BooleanAnswerView isOptional not functioning as expected.

### ISSUE THREAD

**Issue by 5Gears0Chill** [QuickBirdEng/survey_kit#119]
I assume that when the isOptional flag is net to false, then even if there is no start value given the next button should be set to invalid.

One issue is the following 

```dart
isValid: widget.questionStep.isOptional || _result != null,
```
`result` should always be not null? 

i propose this 

```dart
    isValid: widget.questionStep.isOptional ||
          (_result != BooleanResult.NONE && _result != null),
```
this provides the expected behavior

**Comment by Numoy** [comment]
Thanks for providing the fix. I fixed it in main and will plan it in for the next release!
