### ISSUE TITLE
Question: Any way to pick up intermediary results?

### ISSUE THREAD

**Issue by petcupaula** [QuickBirdEng/survey_kit#123]
Hi there. Loving the package, keep it up!

Have a question: is there a way to pick up result values from steps before the end of the survey? The use case I have is that I would like to compute some intermediary scores based on values picked in questions, and then dependent on those scores show the right final question. I could add Navigation Rules where I pick up the value and move to next step, but I see it more of a hack and also an annoyance when having a lot of questions. So, any other way to do it?

**Comment by Numoy** [comment]
You can use the SurveyController with its three methods:
- onNextStep()
- onStepBack()
- onCloseSurvey()

With those three methods, you can observe the current state of the survey.
