### ISSUE TITLE
Is it possible to save the results  as we go to the next question so that problems wont arise if its a very lengthy survey?

### ISSUE THREAD

**Issue by Shruthi125** [QuickBirdEng/survey_kit#124]
Is there a way to save  result values from steps before the end of the survey? 
Is it possible to make drop down selection button using customise step in this survey kit?

**Comment by Numoy** [comment]
You can use the SurveyController with its three methods:
- onNextStep()
- onStepBack()
- onCloseSurvey()

With those three methods you can observe the current state of the survey.
