### ISSUE TITLE
example app does not build/run

### ISSUE THREAD

**Issue by pmagnuson** [QuickBirdEng/survey_kit#130]
Getting this error on both Web and Android device

```
: Error: The argument type 'bool?' can't be assigned to the parameter type 'bool' because 'bool?' is nullable and 'bool' isn't.
platform.dart:294
      semanticsDismissible: cupertino?.semanticsDismissible,
```

my flutter doctor attached
[doctor.log](https://github.com/QuickBirdEng/survey_kit/files/12665410/doctor.log)

**Comment by Joshua27** [comment]
I think the problem is the old version of `flutter_platform_widgets`.
I created a pull request that fixes the build: https://github.com/QuickBirdEng/survey_kit/pull/133

**Comment by Numoy** [comment]
The PR is merged now can you please retry if now works for you @pmagnuson ?

**Comment by pmagnuson** [comment]
unfortunately same basic issue.

```log
Automatically signing iOS for device deployment using specified development team in Xcode project: 7T59ST756H
Xcode build done.                                            5.9s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../../../../.pub-cache/hosted/pub.dev/flutter_platform_widgets-2.2.6/lib/src/platform.dart:294:29: Error: The argument type 'bool?' can't be assigned to the parameter type 'bool' because 'bool?' is nullable and 'bool' isn't.
platform.dart:294

Error launching application on iPhone12.
Exited
```

Same issue on Android device.

I have run `flutter clean; flutter pub get` and `pod update`.  Same issue

**Comment by Joshua27** [comment]
@pmagnuson Your build still uses the old version. I think you can delete the cached version in `../../../../../.pub-cache/hosted/pub.dev/flutter_platform_widgets-2.2.6` and then run `flutter packages get` in your project.

**Comment by pmagnuson** [comment]
same error.  I ran into this on another app so it's probably something on my machine.  Thanks for looking into it.
