### ISSUE TITLE
How can I have several questions in a single step?

### ISSUE THREAD

**Issue by samihoucheimi** [QuickBirdEng/survey_kit#31]
I am looking for a way to have multiple questions in a single QuestionStep which would result in a better user experience in my case. Is there a clear way to do so or would this be considered a CustomStep?
Thanks!

**Comment by Numoy** [comment]
Currently it is not possible to include several steps in on QuestionStep, but we plan to make that possible in the future.

**Comment by Numoy** [comment]
Relate to #23: This will be included in the next feature release!
