### ISSUE TITLE
Survey answer access

### ISSUE THREAD

**Issue by michaelbc** [QuickBirdEng/survey_kit#39]
Hi,

Can you show me how to access the survey answers with sample code in Dart/Flutter?

Thanks,
Mike

**Comment by hsattar12** [comment]
Hello,

I've also been struggling to access scale question answers. I want to add them up and display the score on the completion page.

Thank you!

**Comment by Numoy** [comment]
Hi, 

currently the steps are not part of the result but we will change that in the future. Right now also the results are not serializable out of the box. You need to parse them yourself:

**Comment by furkankaradas** [comment]
Hi,

We can access the result when every question is answered?

Thanks.

**Comment by pambasange** [comment]
Hi, 

I can not see the results in last widget called by CompletionStep function. Are there anything that we need to do to get the result in the last screen?

Thank you
