### ISSUE TITLE
custom step

### ISSUE THREAD

**Issue by yurybo** [QuickBirdEng/survey_kit#56]
great package, thank you!
2 questions:
-- would you demonstrate a custom step for attaching images to the step (no need to demo image picker);
-- how to restart the survey, possibly from a specific step (in case if user decided to change some answers).
thank you in advance!
yury

**Comment by Numoy** [comment]
We will enhance the documentation for creating custom steps in the next release!
 Second Question: Have a looks at how the routing works especially the 'NavigableTask'. You can find an example the example application.
