### ISSUE TITLE
SurveyResult toJson

### ISSUE THREAD

**Issue by ezmegy** [QuickBirdEng/survey_kit#79]
Hey guys, 

Awesome plugin, great work!

I've been playing around with it in the last couple of a days and plan on using it in my current project. I would need to export the survey results to json though and saw (on [another thread](https://github.com/QuickBirdEng/survey_kit/issues/39#issuecomment-947547923) + in the code) that it's not implemented yet.

Just wanted to check with you: did you start that at any point?

I took a quick look on how to do it and at this stage I think I would just go ahead, use freezed and make all the subclasses of `QuestionResult` (`BooleanQuestionResult`, `DateQuestionResult` etc) serializable...

Did you maybe see any potential problems with that approach?

Cheers

**Comment by ayushin** [comment]
That'd be great. Either freezed or just json_serializable would be very helpful and it should be a very easy thing to do.

**Comment by ezmegy** [comment]
On the second look, `freezed` didn't seem a natural fit; would have required more refactoring and couldn't use it's full potential.

So I chose to stick with `json_serializable` in the end, that was already a dependency anyway.

Some classes needed custom converters, 
i. e. because of the `QuestionResult` class being `abstract`, see `step_result.dart`,
but wasn't too bad altogether.

**Comment by ezmegy** [comment]
Implemented in
#81 #82 #83 #84
