### ISSUE TITLE
Results not publishing on stepBack and stepForward

### ISSUE THREAD

**Issue by tushkaty** [QuickBirdEng/survey_kit#90]
![simulator_screenshot_9C938B4E-F3ED-40A8-B9C9-D6F93D472E6D](https://user-images.githubusercontent.com/112485044/198027405-dfee43d2-af43-4f27-b758-4115269098c1.png)

I have verified the same issue for all the steps. The result object is stored properly in the example app on the main branch. However, it's coming as null in initState for each step view.

**Comment by JulianSwales** [comment]
I'm also seeing this same problem and not just in the Example app.. If you go all the way back to the beginning, then it does remember the values it had.. However the first time an a question is answered and you come back to it no matter what order of forward and back, it fails to display the correct previously selected value, unless you go all the way back to the beginning..

**Comment by Numoy** [comment]
I will investigate this today. Sorry for the late response!

**Comment by tushkaty** [comment]
@Numoy Looking forward to get a fix on this issue which is critical.

**Comment by Numoy** [comment]
A fix landed in main now. I will create a release for pub.dev soon. Let me know if it fixed the issue for you!

**Comment by tushkaty** [comment]
@Numoy Thank you for the quick resolution. It's working fine for existing steps and custom steps.
